// cyclic_velocity: a velocity ramp generated by the master, Cyclic
// Synchronous Velocity. The drive's velocity loop makes the motor follow it
// and brakes actively when the target returns to zero.
//
//   cyclic_velocity <master.dcf> [interface=can0] [node-id=2] [rpm=1000]
//
// The kind of loop a rover wheel runs.

#include <algorithm>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <thread>

#include "epos4/hardware/Epos4.hpp"

using namespace std::chrono_literals;

namespace
{
volatile std::sig_atomic_t gStop = 0;
void OnSignal(int) {gStop = 1;}

constexpr auto kPeriod = 10ms;  // the SYNC period of the network (sync_period: 10000 us)
}  // namespace

int main(int argc, char ** argv)
{
  if (argc < 2) {
    std::fprintf(stderr, "usage: %s <master.dcf> [interface] [node-id] [rpm]\n", argv[0]);
    return 2;
  }
  const double target = argc > 4 ? std::atof(argv[4]) : 1000.0;  // rpm at the motor
  std::signal(SIGINT, OnSignal);

  epos4::CanBus bus{{argc > 2 ? argv[2] : "can0", argv[1], 1}};
  epos4::Epos4 motor{bus, static_cast<std::uint8_t>(argc > 3 ? std::atoi(argv[3]) : 2)};
  bus.Start();

  if (!motor.WaitUntilReady()) {
    std::printf("no answer from the drive\n");
    return 1;
  }
  for (int i = 0; i < 40 && !motor.IsPdoActive(); ++i) {std::this_thread::sleep_for(50ms);}
  if (!motor.IsPdoActive()) {
    std::printf("no PDOs: the cyclic modes need the mapping from the DCF\n");
    return 1;
  }

  // The drive interpolates between setpoints over this window: it must match
  // the SYNC period.
  epos4::configs::CyclicConfigs cyclic;
  cyclic.interpolationTimePeriodMs = 10;
  motor.GetConfigurator().Apply(cyclic);

  if (!motor.Enable()) {
    std::printf("enable failed: %s\n", motor.DescribeLastError().c_str());
    return 1;
  }
  // Starts publishing on every SYNC, from 0 rpm: no jump.
  if (auto ec = motor.EnterCyclicVelocityMode()) {
    std::printf("cannot enter CSV: %s\n", ec.message().c_str());
    motor.Disable();
    return 1;
  }

  // Trapezoid: 0.5 s up, 2 s at speed, 0.5 s down.
  const double ramp = 0.5;
  const double hold = 2.0;
  const auto start = std::chrono::steady_clock::now();
  auto next = start;
  for (int cycle = 0; ; ++cycle) {
    const double t = std::chrono::duration<double>(std::chrono::steady_clock::now() - start).count();
    double factor = std::min(t / ramp, 1.0);
    if (t > ramp + hold) {factor = std::max(0.0, 1.0 - (t - ramp - hold) / ramp);}
    if (gStop) {factor = 0.0;}

    // Lock-free: stores an atomic the bus thread publishes on the next SYNC.
    motor.StageTargetVelocity(static_cast<std::int32_t>(target * factor));

    // Worth checking every cycle: cached values keep reading back even when
    // the bus has gone quiet.
    if (!motor.IsCyclicHealthy()) {
      std::printf("axis stopped responding or left Operation enabled\n");
      break;
    }
    if (cycle % 20 == 0) {
      std::printf("  t=%4.2fs  target=%6.0f  actual=%6d rpm\n",
        t, target * factor, motor.GetCachedVelocity());
    }
    if (factor == 0.0 && t > ramp) {break;}

    next += kPeriod;
    std::this_thread::sleep_until(next);
  }

  // The target is 0 rpm and the drive is braking: wait for standstill.
  const auto deadline = std::chrono::steady_clock::now() + 2s;
  while (std::abs(motor.GetCachedVelocity()) > 10 && std::chrono::steady_clock::now() < deadline) {
    std::this_thread::sleep_for(kPeriod);
  }

  motor.ExitCyclicMode();
  motor.Disable();
  bus.Stop();
  return 0;
}
