// step_response: command a reference and record how the axis follows it, to
// a CSV file - the raw material for tuning gains and for plotting.
//
//   step_response <master.dcf> <interface> <node-id> <mode> <out.csv>
//
// mode:
//   profile    a Profile Position move of 20000 qc   (trapezoid generated by the drive)
//   velocity   a 0 -> 1000 rpm -> 0 trapezoid in CSV (generated here, one point per SYNC)
//   position   a 20-degree sine in CSP at the output (generated here)
//   torque     a 0.05 N m torque step in CST, with a 1500 rpm limit
//
// Columns: t [s], target, position [qc], velocity [rpm], torque [per mille], statusword.
// The target is in the unit of the mode: qc, rpm, qc, per mille.

#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <thread>

#include <ros2units/units.h>

#include "epos4/hardware/Epos4.hpp"

using namespace std::chrono_literals;
using namespace units::literals;
using Clock = std::chrono::steady_clock;

namespace
{

constexpr auto kPeriod = 10ms;   // the SYNC period
constexpr double kPi = 3.14159265358979323846;

struct Recorder
{
  std::FILE * file;
  Clock::time_point start;

  void Row(const epos4::Epos4 & motor, double target) const
  {
    const double t = std::chrono::duration<double>(Clock::now() - start).count();
    std::fprintf(file, "%.3f,%.1f,%d,%d,%d,0x%04X\n", t, target,
      motor.GetCachedPosition(), motor.GetCachedVelocity(),
      motor.GetCachedTorque(), motor.GetCachedStatusword());
  }
};

// Runs `step(t)` once per period for `seconds`, recording after each step.
template<typename Step>
void Loop(epos4::Epos4 & motor, const Recorder & rec, double seconds, Step step)
{
  auto next = Clock::now();
  while (true) {
    const double t = std::chrono::duration<double>(Clock::now() - rec.start).count();
    if (t > seconds) {break;}
    rec.Row(motor, step(t));
    next += kPeriod;
    std::this_thread::sleep_until(next);
  }
}

}  // namespace

int main(int argc, char ** argv)
{
  if (argc < 6) {
    std::fprintf(stderr,
      "usage: %s <master.dcf> <interface> <node-id> <profile|velocity|position|torque> <out.csv>\n",
      argv[0]);
    return 2;
  }
  const std::string mode = argv[4];

  epos4::CanBus bus{{argv[2], argv[1], 1}};
  epos4::Epos4 motor{bus, static_cast<std::uint8_t>(std::atoi(argv[3]))};
  motor.SetMechanism(2000, 1.0 / 100.0);
  bus.Start();

  if (!motor.WaitUntilReady()) {
    std::fprintf(stderr, "no answer from the drive\n");
    return 1;
  }
  for (int i = 0; i < 40 && !motor.IsPdoActive(); ++i) {std::this_thread::sleep_for(50ms);}

  epos4::configs::CyclicConfigs cyclic;
  cyclic.interpolationTimePeriodMs = 10;
  motor.GetConfigurator().Apply(cyclic);

  if (!motor.Enable()) {
    std::fprintf(stderr, "enable failed: %s\n", motor.DescribeLastError().c_str());
    return 1;
  }

  std::FILE * file = std::fopen(argv[5], "w");
  if (!file) {
    std::fprintf(stderr, "cannot write %s\n", argv[5]);
    return 1;
  }
  std::fprintf(file, "t,target,position,velocity,torque,statusword\n");
  Recorder rec{file, Clock::now()};
  const std::int32_t origin = motor.GetPosition().Refresh().GetValue();

  if (mode == "profile") {
    epos4::configs::MotionProfileConfigs profile;
    profile.profileVelocity = 1500;      // rpm
    profile.profileAcceleration = 3000;  // rpm/s
    profile.profileDeceleration = 3000;
    motor.GetConfigurator().Apply(profile);
    const double target = origin + 20000.0;
    rec.start = Clock::now();
    Loop(motor, rec, 0.3, [&](double) {return static_cast<double>(origin);});
    motor.SetControl(epos4::controls::ProfilePosition{}
                       .WithPosition(static_cast<std::int32_t>(target)));
    Loop(motor, rec, 2.4, [&](double) {return target;});
  } else if (mode == "velocity") {
    motor.EnterCyclicVelocityMode();
    rec.start = Clock::now();
    Loop(motor, rec, 3.0, [&](double t) {
        double f = 0.0;
        if (t > 0.2 && t < 0.7) {f = (t - 0.2) / 0.5;}
        else if (t >= 0.7 && t < 2.0) {f = 1.0;}
        else if (t >= 2.0 && t < 2.5) {f = 1.0 - (t - 2.0) / 0.5;}
        const double target = 1000.0 * f;
        motor.StageTargetVelocity(static_cast<std::int32_t>(target));
        return target;
      });
  } else if (mode == "position") {
    motor.EnterCyclicPositionMode();
    const auto & mechanism = motor.GetMechanism();
    rec.start = Clock::now();
    Loop(motor, rec, 4.0, [&](double t) {
        const units::angle::degree_t offset{20.0 * std::sin(2.0 * kPi * 0.5 * t)};
        const std::int32_t target = origin + mechanism.ToQuadCounts(offset);
        motor.StageTargetPosition(target);
        return static_cast<double>(target);
      });
  } else if (mode == "torque") {
    auto & rated = motor.GetMotorRatedTorque().Refresh();
    if (rated.GetStatus() || rated.GetValue() == 0) {
      std::fprintf(stderr, "rated torque is 0: configure the motor data\n");
      std::fclose(file);
      return 1;
    }
    motor.EnterCyclicTorqueMode();
    rec.start = Clock::now();
    bool limited = false;
    Loop(motor, rec, 2.5, [&](double t) {
        limited = limited || std::abs(motor.GetCachedVelocity()) > 1500;
        const bool on = t > 0.2 && t < 1.5 && !limited;
        const std::int16_t target = on ? *motor.TorqueToPerThousand(0.05_Nm) : std::int16_t{0};
        motor.StageTargetTorque(target);
        return static_cast<double>(target);
      });
  } else {
    std::fprintf(stderr, "unknown mode %s\n", mode.c_str());
  }

  std::fclose(file);
  motor.ExitCyclicMode();
  motor.Disable();
  bus.Stop();
  std::printf("recorded %s to %s\n", mode.c_str(), argv[5]);
  return 0;
}
