#!/usr/bin/env python3
"""Generates the API reference - one page per class - from EposLib's headers.

    scripts/gen_api.py path/to/EposLib docs/reference/api

Every public member with the comment block above it, grouped by the
section banners of the header. Overloads are listed under one heading.
"""

import re
import sys
from pathlib import Path

HEADER = "<!-- Generated by scripts/gen_api.py from EposLib's headers. Do not edit. -->\n\n"

CLASSES = [
    # (file, class, page, title, intro)
    ("include/epos4/CanBus.hpp", "CanBus", "canbus", "CanBus",
     "One CAN network and its CANopen master. `#include \"epos4/CanBus.hpp\"` "
     "(also brought in by `Epos4.hpp`). See [Bus and device lifecycle](../../api/lifecycle.md)."),
    ("include/epos4/hardware/Epos4.hpp", "Epos4", "epos4", "Epos4",
     "One EPOS4 on a bus: state machine, control, status signals, I/O, diagnostics and the "
     "lock-free cyclic path. `#include \"epos4/hardware/Epos4.hpp\"`."),
    ("include/epos4/hardware/Epos4.hpp", "Configurator", "configurator", "Configurator",
     "Applies configuration groups to a device and reads them back, reached through "
     "`Epos4::GetConfigurator()`. See [Configuration](../../api/configuration.md) and "
     "[Configuration fields](../configuration-fields.md)."),
    ("include/epos4/hardware/Encoder.hpp", "Encoder", "encoder", "Encoder",
     "The feedback subsystem of a device, reached through `Epos4::GetEncoder()`. "
     "`#include \"epos4/hardware/Encoder.hpp\"`. See [Encoders](../../api/encoders.md)."),
    ("include/epos4/signals/StatusSignal.hpp", "StatusSignal", "status-signal", "StatusSignal<T>",
     "A value read from the drive with its status and timestamp. See "
     "[Status signals](../../api/status-signals.md)."),
    ("include/epos4/core/UnitConversion.hpp", "MechanismScale", "mechanism-scale", "MechanismScale",
     "Encoder resolution and gear ratio: the conversion between drive units and physical "
     "quantities. See [Units](../../concepts/units.md)."),
]

SEPARATOR = re.compile(r"^\s*// -{10,}\s*$")


def clean_comment(lines):
    text = []
    for line in lines:
        s = line.strip()
        if s.startswith("//"):
            s = s[2:]
            if s.startswith(" "):
                s = s[1:]
        text.append(s)
    # Indented lines (code samples in comments) become a code block.
    out, code = [], []
    for t in text + [""]:
        if t.startswith("  ") and t.strip():
            code.append(t[2:])
            continue
        if code:
            out.append("```cpp\n" + "\n".join(code) + "\n```")
            code = []
        out.append(t)
    para = "\n".join(out).strip()
    return re.sub(r"\n{3,}", "\n\n", para)


def class_body(text, name):
    m = re.search(r"\n(?:template<[^>]*>\s*\n)?class " + name + r"\b[^;{]*\{", text)
    if not m:
        raise SystemExit(f"class {name} not found")
    i = m.end()
    depth = 1
    j = i
    while depth:
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
        j += 1
    return text[i:j - 1]


def method_name(signature):
    m = re.search(r"(operator\S*|~?\w+)\s*\(", signature)
    return m.group(1) if m else signature.split()[0]


def parse(body):
    """Yields ('section', title, text) and ('member', name, signature, doc)."""
    lines = body.splitlines()
    i = 0
    access = "private"
    comments = []
    items = []
    depth = 0
    while i < len(lines):
        line = lines[i]
        s = line.strip()
        if depth == 0 and s in ("public:", "private:", "protected:"):
            access = s[:-1]
            comments = []
            i += 1
            continue
        if depth == 0 and SEPARATOR.match(line):
            # A banner: separator, comment lines, separator.
            j = i + 1
            block = []
            while j < len(lines) and not SEPARATOR.match(lines[j]) and lines[j].strip().startswith("//"):
                block.append(lines[j])
                j += 1
            if j < len(lines) and SEPARATOR.match(lines[j]) and access == "public":
                text = clean_comment(block)
                first, _, rest = text.partition("\n")
                depth_p, cut = 0, len(first)
                for k, ch in enumerate(first):
                    depth_p += ch == "("
                    depth_p -= ch == ")"
                    if depth_p == 0 and (first[k:k + 2] in (". ", ", ") or ch == ":"):
                        cut = k
                        break
                title = first[:cut].strip().rstrip(".")
                lead = first[cut:].lstrip(".,: ").strip()
                body = (lead[:1].upper() + lead[1:] + "\n" if lead else "") + rest
                items.append(("section", title, body.strip()))
            comments = []
            i = j + 1
            continue
        if s.startswith("//"):
            comments.append(line)
            i += 1
            continue
        if not s:
            comments = [] if not comments else comments
            i += 1
            continue
        if s.startswith("#define") or s.startswith("#undef"):
            while lines[i].rstrip().endswith("\\"):
                i += 1
            i += 1
            comments = []
            continue
        m = re.match(r"EPOS4_CONFIG_GROUP\((\w+)\)", s)
        if m:
            if access == "public":
                items.append(("group", m.group(1)))
            i += 1
            continue
        if s.startswith(("struct ", "class ", "friend ", "using ", "enum ")) and s.endswith(";"):
            comments = []
            i += 1
            continue
        if s.startswith(("struct ", "enum ")) and not s.endswith(";"):
            # nested type definition: skip its body
            depth_local = s.count("{") - s.count("}")
            i += 1
            while i < len(lines) and (depth_local > 0 or "{" not in lines[i - 1] and depth_local == 0):
                depth_local += lines[i].count("{") - lines[i].count("}")
                i += 1
                if depth_local <= 0 and lines[i - 1].strip().endswith("};"):
                    break
            comments = []
            continue
        # A declaration or an inline definition. A trailing // comment is
        # part of its documentation, not of the code.
        def code_of(raw):
            return raw.split("//", 1)[0].rstrip()
        trailing = []
        if "//" in line:
            trailing.append(line.split("//", 1)[1].strip())
        decl = [code_of(line)]
        while not (decl[-1].endswith(";") or decl[-1].endswith("}") or decl[-1].endswith("{")):
            i += 1
            if "//" in lines[i]:
                trailing.append(lines[i].split("//", 1)[1].strip())
            decl.append(code_of(lines[i]))
        joined = " ".join(d.strip() for d in decl)
        if joined.rstrip().endswith("{"):
            # multi-line inline body: skip to its closing brace
            d = joined.count("{") - joined.count("}")
            while d > 0:
                i += 1
                d += lines[i].count("{") - lines[i].count("}")
            joined = joined[:joined.index("{")].strip() + ";"
        elif "{" in joined and not joined.startswith(("template",)):
            head = joined[:joined.index("{")].strip()
            if ")" in head or "operator" in head:
                joined = head + ";"
        signature = re.sub(r"\s+", " ", joined).replace(" ;", ";")
        if access == "public" and "(" in signature and not signature.startswith("//"):
            doc = clean_comment(comments)
            if trailing:
                doc = (doc + "\n\n" if doc else "") + " ".join(trailing)
            items.append(("member", method_name(signature), signature, doc))
        comments = []
        i += 1
    return items


def render(cls, title, intro, items):
    out = [HEADER, f"# {title}\n\n{intro}\n\n"]
    # merge consecutive overloads with the same name
    merged = []
    for it in items:
        if it[0] == "member" and merged and merged[-1][0] == "member" and merged[-1][1] == it[1]:
            merged[-1] = ("member", it[1], merged[-1][2] + [it[2]], merged[-1][3] or it[3])
        elif it[0] == "member":
            merged.append(("member", it[1], [it[2]], it[3]))
        else:
            merged.append(it)
    groups = [it[1] for it in merged if it[0] == "group"]
    if groups:
        merged = [it for it in merged if it[0] != "group"]
        sigs = []
        for g in groups:
            sigs.append(f"std::error_code Apply(const configs::{g} & config);")
            sigs.append(f"std::error_code Refresh(configs::{g} & config);")
        merged.insert(1, ("member", "Apply / Refresh (per group)", sigs,
                          "One `Apply()` and one `Refresh()` per configuration group. "
                          "`Refresh()` fills every field the group has, from the same list "
                          "of objects `Apply()` writes. Groups: " +
                          ", ".join(f"`{g}`" for g in groups) + "."))
    for it in merged:
        if it[0] == "section":
            out.append(f"## {it[1]}\n\n")
            if it[2]:
                out.append(it[2] + "\n\n")
            continue
        _, name, sigs, doc = it
        out.append(f"### `{name}`\n\n```cpp\n" + "\n".join(sigs) + "\n```\n\n")
        if doc:
            out.append(doc + "\n\n")
    return "".join(out)


def main():
    src = Path(sys.argv[1])
    dest = Path(sys.argv[2])
    dest.mkdir(parents=True, exist_ok=True)
    index = [HEADER, "# API reference\n\n",
             "Every public member of EposLib's classes, with the documentation from its "
             "header. The guides in [API Usage](../../api/index.md) explain how they fit "
             "together; [How EposLib works inside](../../concepts/internals.md) what they do "
             "on the bus.\n\n| Class | |\n|---|---|\n"]
    for path, cls, page, title, intro in CLASSES:
        text = (src / path).read_text()
        items = parse(class_body(text, cls))
        (dest / f"{page}.md").write_text(render(cls, title, intro, items))
        n = sum(1 for it in items if it[0] in ("member", "group"))
        index.append(f"| [`{title}`]({page}.md) | {n} members |\n")
    index.append("\nThe control requests, configuration groups and enumerations are plain "
                 "structs: see [Control requests](../../api/control-requests.md), "
                 "[Configuration fields](../configuration-fields.md) and "
                 "[Enumerations](../enumerations.md).\n")
    (dest / "index.md").write_text("".join(index))


if __name__ == "__main__":
    main()
