#!/usr/bin/env python3
"""Writes docs/examples/<name>.md for every example: description, how to run
it, the source (included from examples/src) and the output of the last run
against epos4_sim, taken from a check_examples.sh log run with SHOW=60.

    scripts/gen_example_pages.py <check_examples.log>
"""

import re
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent

EXAMPLES = [
    ("device_info", "device-info", "Device information",
     "Everything worth checking on a drive before moving it: how the master's boot of the "
     "node went, its identity, whether PDOs flow and both ends agree on their layout, the "
     "state, active and past faults, supply, temperature and motor data. Read-only: it never "
     "enables the motor or changes a parameter - the right first program for a new drive.",
     ["`GetBootStatus()` after `WaitUntilReady()`: a node whose configuration download failed still answers SDO.",
      "`CheckPdoMapping()` turns a silent layout mismatch into a list of differences.",
      "`RefreshAll()` reads several signals concurrently; `IsAllGood()` checks them all.",
      "`Configurator::Refresh(MotorConfigs&)` reads the motor data, including the rated torque the drive computes."],
     "2", None),
    ("profile_position", "profile-position", "Profile position",
     "Point-to-point moves with the drive generating the trapezoidal ramp: an absolute move "
     "in quadcounts, a relative move given as an angle at the output with its own speed, "
     "and back to the start.",
     ["The profile is configured once with `MotionProfileConfigs`; requests only override what differs.",
      "`SetMechanism()` makes `WithPosition(90_deg)` mean 90 degrees at the gearbox output.",
      "`SetControl()` returns once the drive has accepted the target; waiting for *target reached* is separate.",
      "*Target reached* can still be set from the previous move: wait for it to drop first."],
     "2", None),
    ("profile_velocity", "profile-velocity", "Profile velocity",
     "Spin at a velocity, with the drive ramping up and down. The ramp time is velocity / "
     "acceleration. `epos4_sim` does not model Profile Velocity Mode, so this example is only "
     "compiled; run it on hardware.",
     ["There is no handshake in PVM: the target velocity takes effect as soon as it arrives.",
      "`IsAtZeroSpeed()` is Statusword bit 12 under PVM.",
      "Ctrl+C stops the loop and ramps back to zero before disabling."],
     "2 [rpm] [seconds]", None),
    ("cyclic_velocity", "cyclic-velocity", "Cyclic velocity",
     "A trapezoidal velocity profile generated by the program, one setpoint per SYNC, with "
     "the drive's velocity loop making the motor follow it - the loop a rover wheel runs. "
     "When the target returns to zero the drive brakes actively, and the program waits for "
     "standstill before disabling.",
     ["The interpolation time period is set to the SYNC period.",
      "`EnterCyclicVelocityMode()` starts from 0 rpm: no jump.",
      "`StageTargetVelocity()` is lock-free; `IsCyclicHealthy()` is checked every cycle.",
      "`sleep_until` on an absolute time keeps the period exact."],
     "2 [rpm]", None),
    ("cyclic_torque", "cyclic-torque", "Cyclic torque",
     "A torque step through Cyclic Synchronous Torque, given in newton metres, with a "
     "velocity limit that drops the torque to zero. The run below used a simulator whose "
     "rated torque was set to 0.45 N m; 0.05 N m is 111 thousandths of it.",
     ["The rated torque is checked first: if it is 0 the motor data is missing and N m has no meaning.",
      "`EnterCyclicTorqueMode()` starts at the torque the axis already produces, and reads the rated torque once.",
      "`StageTargetTorque(0.05_Nm)` converts without bus access.",
      "On a free shaft any torque above friction accelerates the motor until its no-load speed - guard it."],
     "2 [Nm] [max-rpm]", None),
    ("cyclic_position", "cyclic-position", "Cyclic position",
     "Follow a trajectory computed on the master - a sine wave of 20 degrees around the "
     "starting point, at the gearbox output - with the drive interpolating between "
     "setpoints. The pattern under any trajectory follower.",
     ["`EnterCyclicPositionMode()` seeds the target with the actual position, so the first SYNC holds the axis.",
      "Angles are staged as `units::angle::degree_t`; `GetMechanism().ToAngle()` converts the feedback back.",
      "The actual position trails the target by the two-to-three SYNC latency of the cyclic path."],
     "2 [amplitude-deg]", None),
    ("homing", "homing", "Homing",
     "Give an incremental encoder an absolute zero: map the switches to their inputs, "
     "configure the homing speeds, home on the negative limit switch, then declare a "
     "position without moving with `SetPosition()`.",
     ["`GetSupportedHomingMethods()` lists what the firmware implements.",
      "`Home()` refuses a method whose switch is not mapped, before anything moves.",
      "`IsPositionReferenced()` confirms the reference.",
      "`SetPosition(1000)` uses homing method 37 and restores the homing configuration afterwards."],
     "2", None),
    ("multi_drive", "multi-drive", "Multiple drives",
     "Two drives on one bus - a left and a right wheel at nodes 2 and 3 - driven forward and "
     "then turned in place. Both receive their setpoints on the same SYNC. It uses the "
     "two-drive network in `examples/config/two_drives/bus.yml`, installed with the examples.",
     ["One `CanBus`, every device declared before `Start()`.",
      "`RefreshAll()` over signals of different drives reads them in parallel.",
      "Each wheel is checked with `IsCyclicHealthy()` every cycle."],
     "", "install/eposlib_examples/share/eposlib_examples/config/two_drives/master.dcf"),
    ("fault_monitor", "fault-monitor", "Fault monitor",
     "React to faults as they happen: an emergency callback flags the main loop, which polls "
     "telemetry at 2 Hz, describes any fault with its cause and recovery, and clears it. The "
     "loop a base station status panel runs. (The `0x8220` in the run below is an EMCY the "
     "simulator sends at boot.)",
     ["The callback runs on the CANopen thread: it only sets an atomic flag.",
      "`IsWarning()` filters codes the drive keeps running through.",
      "`ClearsPosition()` says when homing is lost; `ClearFault()` sends the NMT reset a lost heartbeat needs."],
     "2 [seconds]", None),
    ("configuration", "configuration", "Configuration",
     "Read a drive's entire configuration, change three fields, read them back, and save. "
     "Only the fields that are set are written - the gains and motor data read at the start "
     "are untouched.",
     ["`Refresh(Epos4Configuration&)` keeps going past objects absent on this hardware.",
      "`Apply()` validates first and refuses «Power Disable» objects while powered.",
      "`Save()` makes the change survive a power cycle; without `--save` it does not."],
     "2 [--save]", None),
    ("encoder_setup", "encoder-setup", "Encoder setup",
     "Inspect the feedback configuration: which sensor is in each slot, the encoder's "
     "pulses per revolution, the resolution, and the position in degrees at the output. "
     "Read-only. The simulator does not compute the main sensor resolution, so the run below "
     "falls back to computing it from the encoder pulses - the same fallback that is useful "
     "on hardware.",
     ["`Encoder::Refresh()` reads each configuration group in any power state.",
      "`QuadCountsPerRevolution()`: 500 pulses are 2000 quadcounts.",
      "`SetMechanismFromDevice()` takes the resolution from the drive; only the gear ratio is yours."],
     "2 [gear-ratio]", None),
    ("digital_io", "digital-io", "Digital I/O and touch probe",
     "Read the inputs by function and by pin, assign and switch a general purpose output, "
     "read an analog input and set an analog output, then latch the exact position of the "
     "encoder's index pulse with the touch probe while the motor turns past it.",
     ["Function view (`0x60FD`) versus pin view (`0x3141`): the second is for checking wiring.",
      "An output function is assigned to a pin once, then switched by function.",
      "The touch probe latches inside the drive, to encoder resolution."],
     "2", None),
]


def outputs(log_path):
    text = Path(log_path).read_text() if log_path else ""
    result = {}
    current = None
    for line in text.splitlines():
        m = re.match(r"(PASS|FAIL)\s+(\w+)", line)
        if m:
            current = m.group(2)
            result[current] = []
            continue
        if current and line.startswith("      "):
            result[current].append(line[6:])
        elif current and not line.startswith("      "):
            current = None
    return result


def main():
    runs = outputs(sys.argv[1] if len(sys.argv) > 1 else None)
    for name, slug, title, desc, points, args, dcf in EXAMPLES:
        dcf = dcf or "install/eposlib/share/eposlib/config/epos4_network/master.dcf"
        lines = [f"# {title}\n\n{desc}\n\n"]
        lines.append("## Key points\n\n" + "".join(f"- {p}\n" for p in points) + "\n")
        lines.append("## Running it\n\n```bash\n")
        lines.append(f"ros2 run eposlib_examples {name} \\\n  {dcf} can0 {args}".rstrip() + "\n```\n\n")
        lines.append(f"## Source\n\n```cpp title=\"examples/src/{name}.cpp\"\n--8<-- \"src/{name}.cpp\"\n```\n\n")
        out = runs.get(name)
        if out:
            lines.append("## Output against epos4_sim\n\n```text\n" + "\n".join(out).rstrip() + "\n```\n")
        elif name == "profile_velocity":
            lines.append("## Output\n\nNot run in simulation: `epos4_sim` does not model Profile Velocity Mode.\n")
        (DOCS / "docs" / "examples" / f"{slug}.md").write_text("".join(lines))


if __name__ == "__main__":
    main()
