// Writes the device error reference from EposLib's own tables, so the page
// cannot drift from what DescribeDeviceError() prints.
//
//   gen_errors > docs/reference/error-codes.md

#include <cctype>
#include <cstdio>
#include <set>
#include <string>
#include <vector>

#include "epos4/signals/Errors.hpp"
#include "epos4/signals/Identity.hpp"

using namespace epos4::signals;

namespace
{

std::string Escape(const char * text)
{
  std::string out;
  for (const char * p = text; *p; ++p) {
    if (*p == '|') {out += "\\|";} else if (*p == '<') {out += "&lt;";} else {out += *p;}
  }
  return out;
}

std::string Code(const DeviceError & e)
{
  char buf[32];
  if (e.code == e.codeEnd) {
    std::snprintf(buf, sizeof(buf), "0x%04X", e.code);
  } else {
    std::snprintf(buf, sizeof(buf), "0x%04X-0x%04X", e.code, e.codeEnd);
  }
  return buf;
}

const char * Reaction(FaultReaction r)
{
  switch (r) {
    case FaultReaction::kNone: return "-";
    case FaultReaction::kAbortConnectionOption: return "a";
    case FaultReaction::kFaultReactionOption: return "f";
    case FaultReaction::kNoSecureMovement: return "d";
    case FaultReaction::kWarning: return "w";
  }
  return "?";
}

void List(const char * title, const char * const * items, std::size_t count)
{
  std::printf("**%s**\n\n", title);
  for (std::size_t i = 0; i < count; ++i) {
    std::printf("- %s\n", Escape(items[i]).c_str());
  }
  std::printf("\n");
}

}  // namespace

int main(int argc, char ** argv)
{
  const bool hardware = argc > 1 && std::string(argv[1]) == "--hardware";
  if (hardware) {
    std::printf("| Code | Hardware |\n|---|---|\n");
    for (unsigned v = 0; v <= 0xFFFF; ++v) {
      if (const char * name = HardwareName(static_cast<std::uint16_t>(v))) {
        std::printf("| `0x%04X` | %s |\n", v, name);
      }
    }
    return 0;
  }

  std::set<const DeviceError *> seen;
  std::vector<const DeviceError *> errors;
  for (unsigned v = 0; v <= 0xFFFF; ++v) {
    const DeviceError * e = FindDeviceError(static_cast<std::uint16_t>(v));
    if (e && seen.insert(e).second) {errors.push_back(e);}
  }

  std::printf(
    "<!-- Generated by scripts/gen_errors.cpp from EposLib's Errors.cpp. Do not edit. -->\n\n"
    "# Device error codes\n\n"
    "All %zu entries of Table 7-186 of the EPOS4 Firmware Specification, with the cause, "
    "effect and recovery of sections 7.2.1 to 7.2.72. This is what "
    "`Epos4::DescribeLastError()` and `signals::DescribeDeviceError()` print.\n\n"
    "**Reaction** is the manual's fault reaction code:\n\n"
    "| | Meaning |\n|---|---|\n"
    "| **a** | Abort connection option code (`0x6007`, `StopOptionConfigs::abortConnectionOption`) |\n"
    "| **f** | Fault reaction option code (`0x605E`, `StopOptionConfigs::faultReaction`) |\n"
    "| **d** | A secure movement is no longer possible: the drive is disabled regardless |\n"
    "| **w** | Warning: no effect on the device state (`signals::IsWarning()`) |\n\n"
    "**Clears position** means resetting the error loses the homing reference "
    "(`signals::ClearsPosition()`). **NMT reset** means the recovery starts with an NMT "
    "reset communication, which `Epos4::ClearFault()` sends for you "
    "(`signals::RequiresCommunicationReset()`).\n\n"
    "## Summary\n\n"
    "| Code | Name | Register | Reaction | Clears position | NMT reset |\n"
    "|---|---|---|---|---|---|\n",
    errors.size());
  for (const auto * e : errors) {
    std::string anchor = Code(*e);
    for (auto & c : anchor) {c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));}
    std::printf("| [`%s`](#%s) | %s | %s | %s | %s | %s |\n",
      Code(*e).c_str(), anchor.c_str(), Escape(e->name).c_str(),
      DescribeErrorRegister(e->errorRegister).c_str(), Reaction(e->faultReaction),
      e->clearsPosition ? "yes" : "", RequiresCommunicationReset(e->code) ? "yes" : "");
  }
  std::printf("\n## Details\n\n");
  for (const auto * e : errors) {
    std::string anchor = Code(*e);
    for (auto & c : anchor) {c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));}
    std::printf("### %s %s { #%s }\n\n", Code(*e).c_str(), Escape(e->name).c_str(),
      anchor.c_str());
    std::printf("Register: %s · Reaction: **%s**%s\n\n",
      DescribeErrorRegister(e->errorRegister).c_str(), Reaction(e->faultReaction),
      e->clearsPosition ? " · **Clears position**" : "");
    List("Cause", e->causes, e->causeCount);
    List("Effect", e->effects, e->effectCount);
    List("Recovery", e->recovery, e->recoveryCount);
  }
  return 0;
}
