#!/usr/bin/env python3
"""Writes docs/examples/<name>.md for every example: description, how to run
it, the source (included from examples/src) and the output of the last run
against epos4_sim, taken from a check_examples.sh log run with SHOW=60.

    scripts/gen_example_pages.py <check_examples.log>
"""

import re
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent

EXAMPLES = [
    ("device_info", "device-info", "Device information",
     "Everything worth checking on a drive before moving it: how the master's boot of the "
     "node went, its identity, whether PDOs flow and both ends agree on their layout, the "
     "state, active and past faults, supply, temperature and motor data. Read-only: it never "
     "enables the motor or changes a parameter - the right first program for a new drive.",
     ["`GetBootStatus()` after `WaitUntilReady()`: a node whose configuration download failed still answers SDO.",
      "`CheckPdoMapping()` turns a silent layout mismatch into a list of differences.",
      "`RefreshAll()` reads several signals concurrently; `IsAllGood()` checks them all.",
      "`Configurator::Refresh(MotorConfigs&)` reads the motor data, including the rated torque the drive computes."],
     "2", None),
    ("profile_position", "profile-position", "Profile position",
     "Point-to-point moves with the drive generating the trapezoidal ramp: an absolute move "
     "in quadcounts, a relative move given as an angle at the output with its own speed, "
     "and back to the start.",
     ["The profile is configured once with `MotionProfileConfigs`; requests only override what differs.",
      "`SetMechanism()` makes `WithPosition(90_deg)` mean 90 degrees at the gearbox output.",
      "`SetControl()` returns once the drive has accepted the target; waiting for *target reached* is separate.",
      "*Target reached* can still be set from the previous move: wait for it to drop first."],
     "2", None),
    ("profile_velocity", "profile-velocity", "Profile velocity",
     "Spin at a velocity, with the drive ramping up and down. The ramp time is velocity / "
     "acceleration. `epos4_sim` does not model Profile Velocity Mode, so this example is only "
     "compiled; run it on hardware.",
     ["There is no handshake in PVM: the target velocity takes effect as soon as it arrives.",
      "`IsAtZeroSpeed()` is Statusword bit 12 under PVM.",
      "Ctrl+C stops the loop and ramps back to zero before disabling."],
     "2 [rpm] [seconds]", None),
    ("cyclic_velocity", "cyclic-velocity", "Cyclic velocity",
     "A trapezoidal velocity profile generated by the program, one setpoint per SYNC, with "
     "the drive's velocity loop making the motor follow it - the loop a rover wheel runs. "
     "When the target returns to zero the drive brakes actively, and the program waits for "
     "standstill before disabling.",
     ["The interpolation time period is set to the SYNC period.",
      "`EnterCyclicVelocityMode()` starts from 0 rpm: no jump.",
      "`StageTargetVelocity()` is lock-free; `IsCyclicHealthy()` is checked every cycle.",
      "`sleep_until` on an absolute time keeps the period exact."],
     "2 [rpm]", None),
    ("cyclic_torque", "cyclic-torque", "Cyclic torque",
     "A torque step through Cyclic Synchronous Torque, given in newton metres, with a "
     "velocity limit that drops the torque to zero. The run below used a simulator whose "
     "rated torque was set to 0.45 N m; 0.05 N m is 111 thousandths of it.",
     ["The rated torque is checked first: if it is 0 the motor data is missing and N m has no meaning.",
      "`EnterCyclicTorqueMode()` starts at the torque the axis already produces, and reads the rated torque once.",
      "`StageTargetTorque(0.05_Nm)` converts without bus access.",
      "On a free shaft any torque above friction accelerates the motor until its no-load speed - guard it."],
     "2 [Nm] [max-rpm]", None),
    ("cyclic_position", "cyclic-position", "Cyclic position",
     "Follow a trajectory computed on the master - a sine wave of 20 degrees around the "
     "starting point, at the gearbox output - with the drive interpolating between "
     "setpoints. The pattern under any trajectory follower.",
     ["`EnterCyclicPositionMode()` seeds the target with the actual position, so the first SYNC holds the axis.",
      "Angles are staged as `units::angle::degree_t`; `GetMechanism().ToAngle()` converts the feedback back.",
      "The actual position trails the target by the two-to-three SYNC latency of the cyclic path."],
     "2 [amplitude-deg]", None),
    ("homing", "homing", "Homing",
     "Give an incremental encoder an absolute zero: map the switches to their inputs, "
     "configure the homing speeds, home on the negative limit switch, then declare a "
     "position without moving with `SetPosition()`.",
     ["`GetSupportedHomingMethods()` lists what the firmware implements.",
      "`Home()` refuses a method whose switch is not mapped, before anything moves.",
      "`IsPositionReferenced()` confirms the reference.",
      "`SetPosition(1000)` uses homing method 37 and restores the homing configuration afterwards."],
     "2", None),
    ("multi_drive", "multi-drive", "Multiple drives",
     "Two drives on one bus - a left and a right wheel at nodes 2 and 3 - driven forward and "
     "then turned in place. Both receive their setpoints on the same SYNC. It uses the "
     "two-drive network in `examples/config/two_drives/bus.yml`, installed with the examples.",
     ["One `CanBus`, every device declared before `Start()`.",
      "`RefreshAll()` over signals of different drives reads them in parallel.",
      "Each wheel is checked with `IsCyclicHealthy()` every cycle."],
     "", "install/eposlib_examples/share/eposlib_examples/config/two_drives/master.dcf"),
    ("fault_monitor", "fault-monitor", "Fault monitor",
     "React to faults as they happen: an emergency callback flags the main loop, which polls "
     "telemetry at 2 Hz, describes any fault with its cause and recovery, and clears it. The "
     "loop a base station status panel runs. (The `0x8220` in the run below is an EMCY the "
     "simulator sends at boot.)",
     ["The callback runs on the CANopen thread: it only sets an atomic flag.",
      "`IsWarning()` filters codes the drive keeps running through.",
      "`ClearsPosition()` says when homing is lost; `ClearFault()` sends the NMT reset a lost heartbeat needs."],
     "2 [seconds]", None),
    ("configuration", "configuration", "Configuration",
     "Read a drive's entire configuration, change three fields, read them back, and save. "
     "Only the fields that are set are written - the gains and motor data read at the start "
     "are untouched.",
     ["`Refresh(Epos4Configuration&)` keeps going past objects absent on this hardware.",
      "`Apply()` validates first and refuses «Power Disable» objects while powered.",
      "`Save()` makes the change survive a power cycle; without `--save` it does not."],
     "2 [--save]", None),
    ("encoder_setup", "encoder-setup", "Encoder setup",
     "Inspect the feedback configuration: which sensor is in each slot, the encoder's "
     "pulses per revolution, the resolution, and the position in degrees at the output. "
     "Read-only. The simulator does not compute the main sensor resolution, so the run below "
     "falls back to computing it from the encoder pulses - the same fallback that is useful "
     "on hardware.",
     ["`Encoder::Refresh()` reads each configuration group in any power state.",
      "`QuadCountsPerRevolution()`: 500 pulses are 2000 quadcounts.",
      "`SetMechanismFromDevice()` takes the resolution from the drive; only the gear ratio is yours."],
     "2 [gear-ratio]", None),
    ("digital_io", "digital-io", "Digital I/O and touch probe",
     "Read the inputs by function and by pin, assign and switch a general purpose output, "
     "read an analog input and set an analog output, then latch the exact position of the "
     "encoder's index pulse with the touch probe while the motor turns past it.",
     ["Function view (`0x60FD`) versus pin view (`0x3141`): the second is for checking wiring.",
      "An output function is assigned to a pin once, then switched by function.",
      "The touch probe latches inside the drive, to encoder resolution."],
     "2", None),
    ("step_response", "step-response", "Step response",
     "Command a reference and record how the axis follows it, to CSV: the raw material for "
     "tuning gains and for the plots of this documentation. Four modes: a Profile Position "
     "move, a CSV velocity trapezoid, a CSP sine, and a CST torque step.",
     ["Records the lock-free cached feedback every SYNC period - no bus traffic added.",
      "The target column is in the mode's own unit, so target and actual compare directly.",
      "Change one gain, record again, overlay the two CSVs: that is tuning."],
     "2 velocity out.csv", None),
    ("telemetry_logger", "telemetry-logger", "Telemetry logger",
     "Record a drive's health - supply, temperature, current, I2t, PWM duty cycle, state, last "
     "EMCY - to CSV at a fixed rate. What a rover logs on every drive during a run, to know "
     "afterwards why a joint stopped. Read-only.",
     ["One `RefreshAll()` per row: every value of the row comes from the same moment.",
      "A value whose read failed is left empty, never filled with a stale number.",
      "`fflush` after each row: the file survives a crash or a pulled battery."],
     "2 run.csv 60 5", None),
]


WALK = {
"device_info": """1. **Bus and device.** `CanBus` gets the interface, the master DCF and the master's node-ID; the `Epos4` is declared before `Start()` so the master routes its PDOs.
2. **`WaitUntilReady()`** blocks until the node answers an SDO request (5 s at most).
3. **Boot status.** The boot completes shortly after the first SDO answer, so the program polls `GetBootStatus().count` for up to 2 s. `'L'` (*already operational*) is advisory; any other letter means the configuration download did not complete.
4. **Identity** - four SDO reads of `0x1018`, plus `0x1000`, `0x1008`, `0x2100`, `0x1F56`, `0x1F57` - rendered with the hardware name and the firmware file name.
5. **PDOs.** `IsPdoActive()` turns true on the first TPDO; `CheckPdoMapping()` reads the eight PDO channels over SDO and compares them with the master's concise DCF.
6. **State, faults, history.** `IsFaulted()` triggers `DescribeLastError()`; the history (`0x1003`) survives a fault reset.
7. **Power.** `RefreshAll()` reads supply, temperature and current concurrently.
8. **Motor data.** `Refresh(MotorConfigs&)` reads `0x6402`, `0x3001`, `0x3002` and the computed rated torque `0x6076`.""",
"profile_position": """1. **Mechanism before start.** `SetMechanism(2000, 1/100)` makes quantities convertible; it touches nothing on the bus.
2. **Profile once.** `Apply(MotionProfileConfigs)` writes `0x6081`, `0x6083`, `0x6084`; every later move inherits them.
3. **Enable** walks the state machine to *Operation enabled* (three Controlword commands).
4. **Move 1** - `SetControl(ProfilePosition{}.WithPosition(start + 10000))`: switches to mode 1 if needed, puts the target in RPDO1, and performs the setpoint handshake. It returns when the drive has *accepted* the target.
5. **`WaitForTarget()`** waits for *target reached* to drop (it may still be set from before) and then to rise, watching for a fault meanwhile.
6. **Move 2** is relative and in degrees at the output: 90° through 1:100 is 25 motor turns = 50 000 qc, at a 1500 rpm override (written to `0x6081` before the handshake).
7. **Back to the start, disable.**

On hardware, watch `GetFollowingError()` during the moves: it should stay well inside `LimitConfigs::followingErrorWindow`.""",
"profile_velocity": """1. **Enable**, then **`SetControl(ProfileVelocity)`**: mode 3, the acceleration and deceleration overrides, and the target velocity into RPDO2. There is no handshake in PVM.
2. **Monitor** velocity and averaged current every 200 ms - the current shows what holding that speed costs.
3. **Stop on the ramp:** a target of 0, then wait for *speed is zero* (Statusword bit 12 in PVM).
4. **Disable.**

The ramp takes `rpm / acceleration` seconds each way. See [Motion profiles](../epos4/motion-profiles.md).""",
"cyclic_velocity": """1. **PDOs are mandatory** for the cyclic modes - the program checks `IsPdoActive()` and stops otherwise.
2. **Interpolation period = SYNC period** (`CyclicConfigs::interpolationTimePeriodMs = 10`), or the drive steps between setpoints.
3. **`EnterCyclicVelocityMode()`** switches to mode 9 once (SDO) and starts publishing 0 rpm on every SYNC.
4. **The loop** computes the trapezoid, stages it (an atomic store), checks `IsCyclicHealthy()`, and sleeps until the next absolute 10 ms tick.
5. **Braking:** with the target at 0 the drive's velocity loop brakes actively; the program waits until the cached velocity is under 10 rpm before `ExitCyclicMode()` and `Disable()`.""",
"cyclic_torque": """1. **Rated torque first.** Every CST value is relative to `0x6076`; a 0 means the motor data is missing and the program refuses to run.
2. **`EnterCyclicTorqueMode()`** seeds the published torque with the torque the axis produces now and reads the rated torque once.
3. **The loop** stages `0.05_Nm` - converted to thousandths with the rated torque read at entry, no bus access - and checks two things every cycle: the velocity limit and `IsCyclicHealthy()`.
4. **On exit** it stages 0 for five SYNC periods so the zero reaches the drive, then leaves the cyclic mode and disables.

On a free shaft the motor accelerates to its no-load speed; on a blocked one the torque is held. See [Motor and thermal model](../epos4/motor-and-thermal.md).""",
"cyclic_position": """1. **`EnterCyclicPositionMode()`** seeds the target with the actual position, so the first SYNC holds the axis exactly where it is.
2. **The origin** is converted to degrees at the output with `GetMechanism().ToAngle()`.
3. **The loop** stages `origin + 20° sin(2π 0.5 t)` as a `units::angle::degree_t`; `StageTargetPosition()` converts it to quadcounts arithmetically.
4. **Back to the origin** for 300 ms, then exit and disable.

The actual position lags the target by the two-to-three SYNC latency of the cyclic path - visible in the plot below.""",
"homing": """1. **Supported methods** from `0x60E3`.
2. **Map the switches** (`DigitalInputConfigs`): without a mapped switch `Home()` refuses the method rather than search blindly.
3. **Configure the run** (`HomingConfigs`): search speeds, acceleration, offset move, home position.
4. **Polarity check:** a limit switch already active before the run usually means an inverted polarity.
5. **`Home()`** blocks until *homing attained* + *target reached*, or *homing error*, or the timeout.
6. **`SetPosition(1000)`** declares the current position to be 1000 qc without moving, through method 37, and restores the homing configuration.""",
"multi_drive": """1. **One `CanBus`**, two devices at nodes 2 and 3, declared before `Start()`. The DCF (from `config/two_drives/bus.yml`) describes both.
2. **`RefreshAll()`** across the two drives reads both supplies in parallel - each drive has its own SDO channel.
3. **Enable and enter CSV on both.** If either fails, both are disabled.
4. **The loop** stages a velocity per wheel each period: forward, then turn in place. Both setpoints leave in the RPDOs of the same SYNC, so the wheels act together.
5. **Health per wheel** every cycle; stop both if one fails.""",
"fault_monitor": """1. **The emergency callback** is registered before `Start()`. It runs on the CANopen thread, so it only prints and sets an atomic flag - never a blocking call into the device.
2. **Telemetry** at 2 Hz with `RefreshAll()`, plus the lock-free last EMCY code.
3. **On a fault** - flagged by the callback or seen by `IsFaulted()` - describe it from the chapter 7 tables, say whether the reset will clear the position, and `ClearFault()`, which sends the NMT reset communication first for heartbeat and CAN-passive faults.""",
"configuration": """1. **`Refresh(Epos4Configuration&)`** reads every group; objects absent on this hardware are left unset.
2. **A sparse change:** only four fields are set, so only four objects are written - the gains and motor data are untouched.
3. **`Apply()`** validates, refuses «Power Disable» objects while powered, and stops at the first refused write.
4. **Read back** the two groups changed.
5. **`Save()`** (`0x1010`) only with `--save`: without it the change is gone at the next power cycle.""",
"encoder_setup": """1. **Sensor slots** from `0x3000:01`, and the main sensor resolution `0x3000:05`.
2. **Encoder 1** from `0x3010`: pulses per revolution, converted to quadcounts (×4).
3. **The mechanism** from the drive's resolution, or computed from the pulses when the drive reports 0 (as the simulator does).
4. **The output angle and velocity**, as `units::` quantities.""",
"digital_io": """1. **Inputs**, by name, by function word (`0x60FD`) and by pin (`0x3141:01`).
2. **Output A** assigned to output 1 (`0x3151:01`), switched on, read back by function and by pin, switched off.
3. **Analog:** input 1 in volts; general purpose output A set to 1.5 V.
4. **Touch probe** armed on the index pulse, then a relative move of 4000 qc so the index passes; the latched position and edge count are read back and the probe disarmed.""",
"step_response": """1. **Choose a mode** on the command line; the recorder writes one row per SYNC period from the cached (PDO) feedback.
2. **profile** - a PPM move: the drive generates the ramp. (`epos4_sim` moves PPM at a fixed slow rate, so this trace is only meaningful on hardware.)
3. **velocity** - a trapezoid staged every period in CSV.
4. **position** - a 20° sine in CSP.
5. **torque** - a 0.05 N·m step in CST, cut off above 1500 rpm.

Plot the CSV with anything - the documentation's own plots come from `scripts/plots.py`.""",
"telemetry_logger": """1. **Seven signals** refreshed together each row with `RefreshAll()`.
2. **A failed read is an empty field**, so a gap in the log is visible as a gap.
3. **The last EMCY** comes from the lock-free cache, which still answers when the node has gone silent.
4. **`fflush` every row.**""",
}

PLOTS = {
"cyclic_velocity": ("step_velocity", "The same kind of trapezoid, recorded with step_response against epos4_sim."),
"cyclic_torque": ("step_torque", "A torque step recorded with step_response against epos4_sim (rated torque 0.45 N m)."),
"cyclic_position": ("step_position", "The sine, recorded with step_response against epos4_sim."),
"step_response": ("step_velocity", "Output of `step_response ... velocity`, plotted."),
}


def outputs(log_path):
    text = Path(log_path).read_text() if log_path else ""
    result = {}
    current = None
    for line in text.splitlines():
        m = re.match(r"(PASS|FAIL)\s+(\w+)", line)
        if m:
            current = m.group(2)
            result[current] = []
            continue
        if current and line.startswith("      "):
            result[current].append(line[6:])
        elif current and not line.startswith("      "):
            current = None
    return result


def main():
    runs = outputs(sys.argv[1] if len(sys.argv) > 1 else None)
    for name, slug, title, desc, points, args, dcf in EXAMPLES:
        dcf = dcf or "install/eposlib/share/eposlib/config/epos4_network/master.dcf"
        lines = [f"# {title}\n\n{desc}\n\n"]
        lines.append("## Key points\n\n" + "".join(f"- {p}\n" for p in points) + "\n")
        if name in WALK:
            lines.append("## Step by step\n\n" + WALK[name] + "\n\n")
        if name in PLOTS:
            plot, caption = PLOTS[name]
            lines.append(f'<figure markdown="span">\n  ![{title}](../assets/plots/{plot}.svg)\n'
                         f'  <figcaption>{caption}</figcaption>\n</figure>\n\n')
        lines.append("## Running it\n\n```bash\n")
        lines.append(f"ros2 run eposlib_examples {name} \\\n  {dcf} can0 {args}".rstrip() + "\n```\n\n")
        lines.append(f"## Source\n\n```cpp title=\"examples/src/{name}.cpp\"\n--8<-- \"src/{name}.cpp\"\n```\n\n")
        out = runs.get(name)
        if name == "step_response":
            out = runs.get("step_velocity")
        if name == "telemetry_logger":
            csv = DOCS / "scripts" / "data" / "telemetry.csv"
            if csv.exists():
                lines.append("## Output against epos4_sim (run.csv)\n\n```text\n" + csv.read_text().strip() + "\n```\n")
            out = None
        if out:
            lines.append("## Output against epos4_sim\n\n```text\n" + "\n".join(out).rstrip() + "\n```\n")
        elif name == "profile_velocity":
            lines.append("## Output\n\nNot run in simulation: `epos4_sim` does not model Profile Velocity Mode.\n")
        (DOCS / "docs" / "examples" / f"{slug}.md").write_text("".join(lines))


if __name__ == "__main__":
    main()
