#!/usr/bin/env python3
"""Generates the reference pages from EposLib's sources.

    scripts/gen_reference.py path/to/EposLib docs/reference

Writes sdo-abort-codes.md, object-dictionary.md, enumerations.md and
configuration-fields.md. Everything is read from the headers and sources, so
the pages always match the library they were generated from.
"""

import re
import sys
from pathlib import Path

HEADER = "<!-- Generated by scripts/gen_reference.py from EposLib. Do not edit. -->\n\n"


def esc(text):
    return text.replace("|", "\\|").replace("<", "&lt;").strip()


# --- SDO abort codes ---------------------------------------------------------

def abort_codes(src):
    text = (src / "src/signals/Errors.cpp").read_text()
    block = text[text.index("kAbortCodes[] = {"):]
    block = block[:block.index("};")]
    rows = re.findall(r'\{0x([0-9A-Fa-f]{8})u,\s*"((?:[^"\\]|\\.)*)",\s*"((?:[^"\\]|\\.)*)"\}', block)
    rows = [(c, n.replace('\\"', '"'), d.replace('\\"', '"')) for c, n, d in rows]
    out = [HEADER, "# SDO abort codes\n\n",
           f"All {len(rows)} codes of Table 7-187. An SDO read or write that the drive refuses "
           "answers with one of these instead of data; the library returns it as the "
           "`std::error_code` of the call, and `signals::DescribeAbortCode()` renders it. "
           "Codes from `0x0F000000` up are maxon specific.\n\n",
           "| Code | Name | Cause |\n|---|---|---|\n"]
    for code, name, cause in rows:
        out.append(f"| `0x{code.upper()}` | {esc(name)} | {esc(cause)} |\n")
    return "".join(out)


# --- object dictionary -------------------------------------------------------

NAMESPACE_TITLES = {
    "comm": "Communication profile (CiA 301) - `od::comm`",
    "maxon_comm": "maxon communication objects - `od::maxon_comm`",
    "maxon": "maxon manufacturer-specific objects - `od::maxon`",
    "cia402": "Device profile (CiA 402) - `od::cia402`",
}


def object_dictionary(src):
    text = (src / "include/epos4/core/ObjectDictionary.hpp").read_text()
    out = [HEADER, "# Object dictionary\n\n",
           "Every object of the EPOS4 that EposLib names, generated from the device EDS "
           "(EPOS4 Module 50/15). Use the constants with `Epos4::ReadObject()` / "
           "`WriteObject()`:\n\n",
           "```cpp\nstd::int16_t raw{};\n"
           "motor.ReadObject(epos4::od::At(epos4::od::cia402::kTorqueActualValue), raw);\n"
           "motor.ReadObject(epos4::od::maxon::kMotorData_NominalCurrent, nominal);  // an Entry\n"
           "```\n\n",
           "An index constant (`std::uint16_t`) needs `od::At(index, subindex)`; "
           "a sub-index constant is already an `od::Entry`. Code written against `od::cia402` "
           "works with any CiA 402 drive; the `maxon` namespaces do not.\n\n"]
    for match in re.finditer(r"namespace (\w+)\n\{(.*?)\n\}  // namespace \1", text, re.S):
        ns, body = match.group(1), match.group(2)
        if ns not in NAMESPACE_TITLES:
            continue
        out.append(f"## {NAMESPACE_TITLES[ns]}\n\n| Index | Sub | Constant | Name |\n|---|---|---|---|\n")
        for line in body.splitlines():
            m = re.match(r"constexpr std::uint16_t (\w+) = 0x([0-9A-Fa-f]{4});", line.strip())
            if m:
                name = re.sub(r"(?<!^)(?=[A-Z])", " ", m.group(1)[1:])
                out.append(f"| `0x{m.group(2).upper()}` | | `{m.group(1)}` | {name} |\n")
                continue
            m = re.match(r"constexpr Entry (\w+) = At\(0x([0-9A-Fa-f]{4}), (\w+)\);\s*//\s*(.*)",
                         line.strip())
            if m:
                sub = m.group(3)
                sub = f"0x{int(sub, 0):02X}" if sub.startswith("0x") or sub.isdigit() else sub
                out.append(f"| `0x{m.group(2).upper()}` | `{sub}` | `{m.group(1)}` | {esc(m.group(4))} |\n")
        out.append("\n")
    return "".join(out)


# --- enumerations ------------------------------------------------------------

def enums(src):
    out = [HEADER, "# Enumerations\n\n",
           "Every enumeration of the public API, with its values and what the source says "
           "about each. The value is what is written to the drive.\n\n"]
    files = [("include/epos4/signals/Enums.hpp", "epos4::signals"),
             ("include/epos4/configs/EncoderConfigs.hpp", "epos4::configs"),
             ("include/epos4/core/Cia402StateMachine.hpp", "epos4::core"),
             ("include/epos4/signals/Errors.hpp", "epos4::signals"),
             ("include/epos4/signals/PdoMapping.hpp", "epos4::signals")]
    for path, ns in files:
        text = (src / path).read_text()
        for m in re.finditer(r"((?://[^\n]*\n)*)enum class (\w+)(?: : ([\w:]+))?\s*\{(.*?)\};", text, re.S):
            comment, name, underlying, body = m.groups()
            doc = " ".join(l.strip()[2:].strip() for l in comment.strip().splitlines()
                           if l.strip().startswith("//") and not set(l.strip()[2:].strip()) <= {"-"})
            out.append(f"## `{ns}::{name}`\n\n")
            if doc:
                out.append(esc(doc) + "\n\n")
            if underlying:
                out.append(f"Underlying type: `{underlying}`.\n\n")
            if "{" not in body and body.count(",") <= 3 and "\n" not in body.strip():
                values = [v.strip() for v in body.split(",") if v.strip()]
                out.append("| Enumerator | Value | Notes |\n|---|---|---|\n")
                for v in values:
                    parts = v.split("=")
                    out.append(f"| `{parts[0].strip()}` | `{parts[1].strip() if len(parts) > 1 else ''}` | |\n")
                out.append("\n")
                continue
            out.append("| Enumerator | Value | Notes |\n|---|---|---|\n")
            pending = []
            for line in body.splitlines():
                s = line.strip()
                if not s:
                    continue
                if s.startswith("//"):
                    pending.append(s[2:].strip())
                    continue
                vm = re.match(r"(k\w+)(?:\s*=\s*([^,/]+))?,?\s*(?://\s*(.*))?", s)
                if vm:
                    note = " ".join(pending + ([vm.group(3)] if vm.group(3) else []))
                    note = note if not set(note) <= {"-", " "} else ""
                    out.append(f"| `{vm.group(1)}` | `{(vm.group(2) or '').strip()}` | {esc(note)} |\n")
                    pending = []
            out.append("\n")
    return "".join(out)


# --- configuration fields ----------------------------------------------------

def config_fields(src):
    out = [HEADER, "# Configuration fields\n\n",
           "Every field of every configuration group, with the object it is written to and "
           "the comment from the source. All fields are `std::optional`: only the ones that "
           "are set are written by `Apply()`, and `Refresh()` fills every one it can read. "
           "Fields marked read-only are filled by `Refresh()` and never written.\n\n"
           "See [Configuration](../api/configuration.md) for how to use them.\n\n"]
    files = ["include/epos4/configs/Configs.hpp", "include/epos4/configs/SystemConfigs.hpp",
             "include/epos4/configs/EncoderConfigs.hpp"]
    for path in files:
        text = (src / path).read_text()
        for m in re.finditer(r"\nstruct (\w+Configs)\n\{(.*?)\n\};", text, re.S):
            name, body = m.group(1), m.group(2)
            # Which object each field is visited with, from Visit().
            objects = {}
            readonly = set()
            visit = body[body.find("static void Visit"):] if "static void Visit" in body else ""
            for vm in re.finditer(r"v(\.ReadOnly|\.template \w+<.*?>)?\(\s*(.*?),\s*s\.(\w+)", visit, re.S):
                kind, obj, field = vm.groups()
                objects.setdefault(field, " ".join(obj.split()))
                if kind == ".ReadOnly":
                    readonly.add(field)
            out.append(f"## `{name}`\n\n| Field | Type | Object | Notes |\n|---|---|---|---|\n")
            pending = []
            fields_part = body[:body.find("template<typename Self")] if "template<typename Self" in body else body
            for line in fields_part.splitlines():
                s = line.strip()
                if s.startswith("//"):
                    pending.append(s[2:].strip())
                    continue
                fm = re.match(r"std::(?:optional<(.+?)>|array<std::optional<(.+?)>, \d+>) (\w+);\s*(?://\s*(.*))?", s)
                if fm:
                    typ = fm.group(1) or (fm.group(2) + "[4]")
                    field = fm.group(3)
                    trailing = fm.group(4) or ""
                    note = " ".join([t for t in pending if t] + ([trailing] if trailing else []))
                    if field in readonly:
                        note = "**Read-only.** " + note
                    obj = objects.get(field, "")
                    if obj.startswith("od::At(") and obj.endswith(")"):
                        obj = obj[len("od::At("):-1].strip()
                    out.append(f"| `{field}` | `{esc(typ)}` | `{esc(obj)}` | {esc(note)} |\n" if obj
                               else f"| `{field}` | `{esc(typ)}` | | {esc(note)} |\n")
                    pending = []
                elif not s:
                    pending = []
                else:
                    pending = []
            out.append("\n")
    return "".join(out)


def main():
    src = Path(sys.argv[1])
    dest = Path(sys.argv[2])
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "sdo-abort-codes.md").write_text(abort_codes(src))
    (dest / "object-dictionary.md").write_text(object_dictionary(src))
    (dest / "enumerations.md").write_text(enums(src))
    (dest / "configuration-fields.md").write_text(config_fields(src))


if __name__ == "__main__":
    main()
