#!/usr/bin/env python3
"""Draws every plot of the documentation into docs/assets/plots/.

    scripts/plots.py

Recorded plots read the CSV traces check_examples.sh leaves in scripts/data/
(epos4_sim, a kinematic model - not a real motor). Analytic plots are drawn
from the formulas the pages derive.
"""

import csv
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "scripts" / "data"
OUT = ROOT / "docs" / "assets" / "plots"
OUT.mkdir(parents=True, exist_ok=True)

RED = "#8b1a1a"
INK = "#1c1c1c"
GREY = "#8a8a8a"
LIGHT = "#d9d4cc"

plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "font.size": 10,
    "axes.edgecolor": INK,
    "axes.labelcolor": INK,
    "axes.titleweight": "bold",
    "axes.titlesize": 11,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.grid": True,
    "grid.color": LIGHT,
    "grid.linewidth": 0.6,
    "xtick.color": INK,
    "ytick.color": INK,
    "legend.frameon": False,
    "svg.fonttype": "none",
    "figure.dpi": 110,
})


PREVIEW = Path(__import__("os").environ["PREVIEW"]) if "PREVIEW" in __import__("os").environ else None


def save(fig, name):
    fig.tight_layout()
    fig.savefig(OUT / f"{name}.svg")
    if PREVIEW:
        fig.savefig(PREVIEW / f"{name}.png")
    plt.close(fig)
    print("wrote", name)


def load(name):
    path = DATA / f"{name}.csv"
    if not path.exists():
        return None
    with path.open() as f:
        rows = list(csv.DictReader(f))
    cols = {k: np.array([float(r[k]) if r[k] and not r[k].startswith("0x") else np.nan
                         for r in rows]) for k in rows[0] if k not in ("statusword", "state", "last_emcy")}
    return cols


# --- recorded --------------------------------------------------------------

def recorded():
    # step_profile.csv is not plotted: epos4_sim moves PPM at a fixed slow rate
    # instead of generating the profile, so the trace would mislead.
    d = None
    if d is not None:
        fig, (a, b) = plt.subplots(2, 1, figsize=(7.5, 4.6), sharex=True)
        a.plot(d["t"], d["target"] - d["target"][0] + 0, color=GREY, ls="--", lw=1.2, label="target")
        a.plot(d["t"], d["position"] - d["position"][0], color=RED, lw=1.8, label="actual position")
        a.set_ylabel("position [qc]")
        a.set_title("Profile Position: a 20 000 qc move at 1500 rpm, 3000 rpm/s")
        a.legend(loc="lower right")
        b.plot(d["t"], d["velocity"], color=RED, lw=1.8, label="actual velocity")
        b.set_ylabel("velocity [rpm]")
        b.set_xlabel("time [s]")
        b.legend(loc="upper right")
        save(fig, "step_profile")

    d = load("step_velocity")
    if d is not None:
        fig, (a, b) = plt.subplots(2, 1, figsize=(7.5, 4.6), sharex=True, gridspec_kw={"height_ratios": [3, 1]})
        a.plot(d["t"], d["target"], color=GREY, ls="--", lw=1.2, label="target (staged every 10 ms)")
        a.plot(d["t"], d["velocity"], color=RED, lw=1.8, label="actual velocity")
        a.set_ylabel("velocity [rpm]")
        a.set_title("Cyclic Synchronous Velocity: a ramp generated by the program")
        a.legend(loc="upper right")
        b.plot(d["t"], d["target"] - d["velocity"], color=INK, lw=1.0)
        b.set_ylabel("error [rpm]")
        b.set_xlabel("time [s]")
        save(fig, "step_velocity")

    d = load("step_position")
    if d is not None:
        qc_per_deg = 2000 * 100 / 360.0
        t0 = d["position"][0]
        fig, (a, b) = plt.subplots(2, 1, figsize=(7.5, 4.6), sharex=True, gridspec_kw={"height_ratios": [3, 1]})
        a.plot(d["t"], (d["target"] - t0) / qc_per_deg, color=GREY, ls="--", lw=1.2, label="target")
        a.plot(d["t"], (d["position"] - t0) / qc_per_deg, color=RED, lw=1.8, label="actual")
        a.set_ylabel("angle at the output [deg]")
        a.set_title("Cyclic Synchronous Position: a 20-degree, 0.5 Hz sine")
        a.legend(loc="upper right")
        b.plot(d["t"], (d["target"] - d["position"]) / qc_per_deg, color=INK, lw=1.0)
        b.set_ylabel("lag [deg]")
        b.set_xlabel("time [s]")
        save(fig, "step_position")

    d = load("step_torque")
    if d is not None:
        fig, (a, b) = plt.subplots(2, 1, figsize=(7.5, 4.6), sharex=True)
        a.plot(d["t"], d["target"], color=GREY, ls="--", lw=1.2, label="target")
        a.plot(d["t"], d["torque"], color=RED, lw=1.8, label="actual torque")
        a.set_ylabel("torque [per mille]")
        a.set_title("Cyclic Synchronous Torque: a 0.05 N m step (rated torque 0.45 N m)")
        a.legend(loc="upper right")
        b.plot(d["t"], d["velocity"], color=INK, lw=1.4, label="velocity - not commanded")
        b.set_ylabel("velocity [rpm]")
        b.set_xlabel("time [s]")
        b.legend(loc="upper right")
        save(fig, "step_torque")


# --- analytic --------------------------------------------------------------

def trapezoid():
    def profile(distance, vmax, acc):
        # distance [rev], vmax [rev/s], acc [rev/s^2]
        t_acc = vmax / acc
        d_acc = 0.5 * acc * t_acc ** 2
        if 2 * d_acc >= distance:            # triangle
            t_acc = np.sqrt(distance / acc)
            vpk = acc * t_acc
            t_total = 2 * t_acc
            t_cruise = 0.0
        else:
            vpk = vmax
            t_cruise = (distance - 2 * d_acc) / vmax
            t_total = 2 * t_acc + t_cruise
        t = np.linspace(0, t_total, 600)
        v = np.where(t < t_acc, acc * t,
                     np.where(t < t_acc + t_cruise, vpk, vpk - acc * (t - t_acc - t_cruise)))
        x = np.concatenate([[0], np.cumsum(v[1:] * np.diff(t))])
        return t, v, x, t_acc, t_cruise

    fig, (a, b) = plt.subplots(2, 1, figsize=(7.5, 4.8), sharex=True)
    for dist, style, label in ((20.0, "-", "20 rev: trapezoid"), (5.0, "--", "5 rev: triangle (v_max never reached)")):
        t, v, x, ta, tc = profile(dist, 1500 / 60, 3000 / 60)
        a.plot(t, v * 60, color=RED if style == "-" else INK, ls=style, lw=1.8, label=label)
        b.plot(t, x, color=RED if style == "-" else INK, ls=style, lw=1.8)
    a.axhline(1500, color=GREY, lw=0.8, ls=":")
    a.text(0.02, 1530, "profile velocity 1500 rpm", color=GREY, fontsize=8)
    a.set_ylabel("velocity [rpm]")
    a.set_title("Trapezoidal profile: v = 1500 rpm, a = d = 3000 rpm/s")
    a.legend(loc="upper right", fontsize=8)
    b.set_ylabel("position [rev]")
    b.set_xlabel("time [s]")
    save(fig, "trapezoid")


def i2t():
    k = np.linspace(1.02, 4.0, 400)
    tp = np.log(k ** 2 / (k ** 2 - 1))
    fig, ax = plt.subplots(figsize=(7.5, 3.8))
    ax.plot(k, tp, color=RED, lw=2)
    ax.plot([2.0], [np.log(4 / 3)], "o", color=INK)
    ax.annotate("k = 2  →  t_p = 0.29 τ\n(manual's example: ≈ 0.3 τ)", (2.0, np.log(4 / 3)),
                xytext=(2.4, 0.9), arrowprops=dict(arrowstyle="->", color=INK), fontsize=9)
    ax.set_xlabel("peak current / nominal current   k = I / I_N")
    ax.set_ylabel("allowed time  t_p / τ_th")
    ax.set_ylim(0, 2.5)
    ax.set_title("I²t: how long a current above nominal can last, from cold")
    save(fig, "i2t_peak")

    D = np.linspace(0.02, 1.0, 400)
    fig, ax = plt.subplots(figsize=(7.5, 3.8))
    for ratio, style in ((0.1, ":"), (1.0, "-"), (10.0, "--")):
        Ton = D * ratio
        allowed = np.sqrt((1 - np.exp(-ratio)) / (1 - np.exp(-Ton)))
        ax.plot(D * 100, allowed, color=RED if ratio == 1.0 else INK, ls=style, lw=1.8,
                label=f"period T = {ratio:g} τ")
    ex = np.sqrt((1 - np.exp(-1)) / (1 - np.exp(-0.1)))
    ax.plot([10], [ex], "o", color=INK)
    ax.annotate(f"T = τ, 10 % on  →  {ex:.2f}·I_N\n(manual's example: 2.6)", (10, ex),
                xytext=(25, 3.6), arrowprops=dict(arrowstyle="->", color=INK), fontsize=9)
    ax.set_xlabel("on-time ratio  D = T_on / T  [%]")
    ax.set_ylabel("allowed I_on / I_N")
    ax.set_ylim(0.8, 6)
    ax.legend(loc="upper right")
    ax.set_title("I²t in a repeating cycle: current allowed during the on-time")
    save(fig, "i2t_duty")


def torque_speed():
    kt = 0.10479            # N m / A, the motor from the team's test
    kn = 30000 / (np.pi * kt * 1000)   # rpm / V
    i_nom = 9.28
    R = 0.6                 # ohm, illustrative terminal resistance
    fig, ax = plt.subplots(figsize=(7.5, 4.0))
    for U, style in ((11.7, "-"), (24.0, "--")):
        u_eff = 0.9 * U     # the EPOS4 outputs at most 0.9 x VCC
        n0 = kn * u_eff
        stall = kt * u_eff / R
        tau = np.linspace(0, min(stall, 3.0), 200)
        n = n0 - (n0 / stall) * tau
        ax.plot(tau, n, color=RED if U < 20 else INK, ls=style, lw=1.8,
                label=f"voltage limit at {U:g} V supply (no-load ≈ {n0:.0f} rpm)")
    ax.axvline(kt * i_nom, color=GREY, ls=":", lw=1.2)
    ax.text(kt * i_nom + 0.02, 80, f"rated torque\n{kt * i_nom:.3f} N m", color=GREY, fontsize=8)
    ax.set_xlim(0, 1.6)
    ax.set_ylim(0, 2400)
    ax.set_xlabel("torque at the motor shaft [N m]")
    ax.set_ylabel("speed [rpm]")
    ax.set_title("Where a motor can operate: below its voltage line")
    ax.legend(loc="upper right", fontsize=8)
    save(fig, "torque_speed")


def bus_load():
    drives = np.arange(1, 13)
    bits = 130e-6
    fig, ax = plt.subplots(figsize=(7.5, 3.6))
    for hz, style in ((100, "-"), (200, "--"), (500, ":")):
        load = (1 + 4 * drives) * bits * hz * 100
        ax.plot(drives, load, color=RED if hz == 100 else INK, ls=style, lw=1.8, marker="o", ms=3,
                label=f"SYNC {hz} Hz")
    ax.axhline(50, color=GREY, lw=1, ls="-.")
    ax.text(8.2, 52, "keep the cyclic load below ~50 %", color=GREY, fontsize=8)
    ax.set_ylim(0, 100)
    ax.set_xlabel("drives on the bus (4 synchronous PDOs each)")
    ax.set_ylabel("bus load at 1 Mbit/s [%]")
    ax.set_title("CAN bus load of the cyclic traffic")
    ax.legend(loc="upper left")
    save(fig, "bus_load")


def pi_step():
    # A PI velocity loop on a first-order mechanical plant J dw/dt = T - b w.
    # Closed loop: J s^2 + (b + Kp) s + Ki, so wn = sqrt(Ki / J) and
    # zeta = (b + Kp) / (2 sqrt(Ki J)). Illustrates the gains, not a real motor.
    dt = 2e-5
    t = np.arange(0, 0.12, dt)
    J, b = 2e-5, 1e-6
    ref = 100.0  # rad/s
    cases = []
    for wn, zeta, style, label in ((200, 1.0, "-", "ζ = 1, ωn = 200 rad/s: fast, no overshoot"),
                                   (50, 1.0, "--", "ζ = 1, ωn = 50 rad/s: low gains, slow"),
                                   (400, 0.35, ":", "ζ = 0.35: I gain too high, overshoot")):
        ki = J * wn ** 2
        kp = 2 * zeta * wn * J - b
        w, integ, out = 0.0, 0.0, []
        for _ in t:
            e = ref - w
            integ += e * dt
            torque = kp * e + ki * integ
            w += (torque - b * w) / J * dt
            out.append(w * 60 / (2 * np.pi))
        cases.append((out, style, label))
    fig, ax = plt.subplots(figsize=(7.5, 3.8))
    for out, style, label in cases:
        ax.plot(t * 1000, out, color=RED if style == "-" else INK, ls=style, lw=1.8, label=label)
    ax.axhline(ref * 60 / (2 * np.pi), color=GREY, lw=0.8, ls="-.")
    ax.set_xlabel("time [ms]")
    ax.set_ylabel("velocity [rpm]")
    ax.set_title("Velocity loop: step response for three PI tunings (illustrative plant)")
    ax.legend(loc="lower right", fontsize=8)
    save(fig, "pi_step")


if __name__ == "__main__":
    recorded()
    trapezoid()
    i2t()
    torque_speed()
    bus_load()
    pi_step()
